services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  backend:
    image: ghcr.io/ngmysamuel/backtester:latest
    command: python -m backtester.worker
    volumes:
      - shared_data:/output/
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  frontend:
    image: ghcr.io/ngmysamuel/backtester:latest
    command: backtester dashboard --is-docker 1
    ports:
      - "8501:8501"
    volumes:
      - shared_data:/output/
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  shared_data: