backtester_settings:
  # benchmark: "ETH-USD"
  benchmark: "SPY"
  period: "10m" # used for live data handling - how long to run
  exchange_closing_time: "16:00" # 24h time format - HH:MM
  cash_buffer: 0.95 # used when clamping order sizes and estimating the if current cash can afford order size - 95%
  initial_capital: 100000.0
  initial_position_size: 1 # used by portfolio to size a trade in the absence of any other signal
  # start_date: "24/11/2025 00:00:00"
  start_date: "15/09/2020 00:00:00"
  end_date: "19/12/2025 00:00:00" # exclusive
  borrow_cost: 0.01 # interest on short sold stock - 1%
  maintenance_margin: 0.3 # margin to hold on short positions - 30%
  risk_per_trade: 0.01 # percentage of total portfolio value willing to risk in a single trade
  base_interval: "1d" # 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo
  metrics_interval: "1d" # the granularity of the output equity curve

risk_manager:
  simple_risk_manager:
    name: backtester.util.risk_manager.simple_risk_manager.SimpleRiskManager
    additional_parameters:
      max_order_quantity: -1
      max_notional_value: -1
      max_daily_loss: 0.05
      max_gross_exposure: -1
      max_net_exposure: -1
      participation_window: 10
      participation_limit: 0.1
      rate_limit: 50 # max orders per second

data_handler:
  yf: 
    name: backtester.data.yf_data_handler.YFDataHandler
  csv:
    name: backtester.data.csv_data_handler.CSVDataHandler
  live:
    name: backtester.data.live_data_handler.LiveDataHandler

position_sizer:
  atr:
    name: backtester.util.position_sizer.atr_position_sizer.ATRPositionSizer
    additional_parameters:
      atr_window: 14 # number of days used when calculating average true range
      atr_multiplier: 2
      # atr_window: 4 # number of days used when calculating average true range
      # atr_multiplier: 10
  no_position_sizer:
    name: backtester.util.position_sizer.no_position_sizer.NoPositionSizer
    additional_parameters:
      constant_position_size: 100

slippage:
  no_slippage:
    name: backtester.util.slippage.no_slippage.NoSlippage
  multi_factor_slippage:
    name: backtester.util.slippage.multi_factor_slippage.MultiFactorSlippage
    additional_parameters:
      periods_in_year: 252
      short_window: 5
      med_window: 21
      long_window: 63
      power_law_exponent: 0.6 # this will be used to indicate a diminishing return i.e. k in x**k. The 3/5 power law by Almgren et al. https://www.cis.upenn.edu/~mkearns/finread/costestim.pdf
      upper_lim_vol_surge: 5 # upper limit on volume surge - prevent excessive impact on model
      bidask_window: 21 # number of days used when calculating bidask spread. https://doi.org/10.1016/j.jfineco.2024.103916
      volatility_cost_factor: 0.2
      market_impact_factor: 0.1
      momentum_cost_factor: 0.05
      liquidity_cost_factor: 0.1
      liquidity_cost_exponent: 0.3
      random_noise: 0.0005

strategies:
  buy_and_hold_simple:
    name: "backtester.strategies.buy_and_hold_simple.BuyAndHoldSimple"
    additional_parameters:
      interval: "1d"
      symbol_list: ["MSFT"]
      rounding_list: [0]
      # interval: "1m"
      # symbol_list: ["BTC-USD"]
      # rounding_list: [8]
      days_before_buying: 5
  moving_average:
    name: "backtester.strategies.moving_average_crossover.MovingAverageCrossover"
    display_name: "Moving Average"
    additional_parameters:
      long_window: 200
      short_window: 50
      interval: "1d"
      symbol_list: ["MSFT"]
      rounding_list: [0]
      # interval: "1m"
      # symbol_list: ["BTC-USD"]
      # rounding_list: [8]